name: i3d-lstm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=pyhd3eb1b0_1
  - alabaster=0.7.12=py36_0
  - asn1crypto=1.4.0=py_0
  - astor=0.8.1=py36_0
  - astroid=2.4.2=py36_0
  - attrs=19.1.0=py_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blosc=1.15.0=h7bd577a_0
  - bzip2=1.0.6=hfa6e2cd_5
  - ca-certificates=2020.12.8=haa95532_0
  - certifi=2020.12.5=py36haa95532_0
  - lazy-object-proxy=1.4.3=py36h2bbff1b_2
  - openssl=1.1.1i=h2bbff1b_0
  - packaging=20.8=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - python=3.6.12=h5500b2f_2
  - pytz=2020.5=pyhd3eb1b0_0
  - setuptools=51.1.2=py36haa95532_3
  - six=1.15.0=py36haa95532_0
  - snappy=1.1.8=h33f27b4_0
  - sqlite=3.33.0=h2a8f88b_0
  - typed-ast=1.4.2=py36h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - webencodings=0.5.1=py36_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - appdirs==1.4.4
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - atomicwrites==1.4.0
    - autopep8==1.5.4
    - bcrypt==3.2.0
    - black==20.8b1
    - cached-property==1.5.2
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.1.1
    - colorama==0.4.4
    - contextlib2==0.6.0.post1
    - cryptography==3.3.1
    - cycler==0.10.0
    - cython==0.29.21
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.6.0
    - diff-match-patch==20200713
    - dm-sonnet==1.20
    - dm-tree==0.1.5
    - docutils==0.16
    - entrypoints==0.3
    - flake8==3.8.4
    - flatbuffers==1.12
    - gast==0.2.2
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - graphs==0.1.3
    - grpcio==1.34.0
    - h5py==3.1.0
    - helpdev==0.7.1
    - html5lib==0.9999999
    - idna==2.10
    - imagesize==1.2.0
    - importlib-metadata==3.4.0
    - intervaltree==3.1.0
    - ipykernel==5.4.3
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isort==5.7.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==1.0.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-applications==1.0.8
    - keras-lookahead==0.9.0
    - keras-preprocessing==1.1.2
    - keras-rectified-adam==0.16.0
    - keyring==21.8.0
    - kiwisolver==1.3.1
    - lxml==4.6.2
    - mahotas==1.4.11
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - mock==4.0.3
    - mypy-extensions==0.4.3
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - networkx==1.8.1
    - notebook==6.2.0
    - numpy==1.19.5
    - numpydoc==1.1.0
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - opt-einsum==3.3.0
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - paramiko==2.7.2
    - parso==0.7.0
    - pathspec==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.2.2
    - pip==19.0.3
    - pluggy==0.13.1
    - progressbar2==3.53.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.10
    - protobuf==3.14.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pycparser==2.20
    - pydocstyle==5.1.1
    - pyfftw==0.12.0
    - pyflakes==2.2.0
    - pygments==2.7.4
    - pylint==2.6.0
    - pyls-black==0.4.6
    - pyls-spyder==0.3.0
    - pynacl==1.4.0
    - pyqt5==5.12.3
    - pyqt5-sip==12.8.1
    - pyqtwebengine==5.12.1
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-jsonrpc-server==0.4.0
    - python-language-server==0.36.2
    - python-utils==2.4.0
    - pywin32==300
    - pywin32-ctypes==0.2.0
    - pywinpty==0.5.7
    - pyyaml==5.3.1
    - pyzmq==20.0.0
    - qdarkstyle==2.8.1
    - qtawesome==1.0.2
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - regex==2020.11.13
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rope==0.18.0
    - rsa==4.7
    - rtree==0.9.7
    - scikit-learn==0.24.0
    - scipy==1.5.4
    - seaborn==0.11.1
    - semantic-version==2.8.5
    - send2trash==1.5.0
    - snowballstemmer==2.0.0
    - sortedcontainers==2.3.0
    - sphinx==3.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - spyder==4.2.1
    - spyder-kernels==1.10.1
    - tabulate==0.8.7
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - textdistance==4.2.0
    - threadpoolctl==2.1.0
    - three-merge==0.1.1
    - toml==0.10.2
    - tornado==6.1
    - traitlets==4.3.3
    - typeguard==2.10.0
    - typing-extensions==3.7.4.3
    - ujson==4.0.1
    - urllib3==1.26.2
    - watchdog==1.0.2
    - wcwidth==0.2.5
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - yapf==0.30.0
    - zipp==3.4.0
prefix: C:\Users\salus\.conda\envs\i3d-lstm

